---
title: "Miscellaneous"
author: "Tobias Messmer"
date: "12/15/2016"
output: html_document
---

```{r}
transition_clust <- unname(cutree(my.tree_naive, k = 3))=="3"
all.pheno <- as.character(sce$phenotype)
all.pheno[match(colnames(sce_naive)[transition_clust], colnames(sce))] <- "transition"
all.pheno <- factor(all.pheno, levels = c("naive", "transition", "primed"))

naive.pheno <- factor(all.pheno[!all.pheno=="primed"], levels=c("naive", "transition"))
y.vs.n <- convertTo(sce[,!all.pheno=="primed"], type="edgeR")
design.vs.n <- model.matrix(~0 + naive.pheno + sce[,!all.pheno=="primed"]$batch)
y.vs.n <- estimateDisp(y.vs.n, design.vs.n, prior.df = 0)
fit.vs.n <- glmFit(y.vs.n, design.vs.n)

chosen.pheno <- which(levels(naive.pheno)=="transition")
result.logFC <- result.PValue <- list()
for (pheno in seq_len(nlevels(naive.pheno))) {
    if (pheno==chosen.pheno) { next }
    contrast <- numeric(ncol(design.vs.n))
    contrast[chosen.pheno] <- 1
    contrast[pheno] <- -1
    res <- glmLRT(fit.vs.n, contrast=contrast)
    con.name <- paste0('vs.', levels(naive.pheno)[pheno]) 
    result.logFC[[con.name]] <- res$table$logFC 
    result.PValue[[con.name]] <- res$table$PValue
}

marker_nt <- cbind(unlist(result.logFC["vs.naive"]), unlist(result.PValue["vs.naive"]))
rownames(marker_nt) <- rownames(y)
colnames(marker_nt) <- c("logFC", "PValue")
marker_nt <- marker_nt[order(marker_nt[,"PValue"]),]
write.table(file=paste0(output, "nvst.marker.tsv"), marker_nt, sep="\t", quote=FALSE, col.names = NA) 

```
Primed vs Trans
```{r}
primed.pheno <- factor(all.pheno[!all.pheno=="naive"], levels=c("transition", "primed"))
y.vs.p <- convertTo(sce[,!all.pheno=="naive"], type="edgeR")
design.vs.p <- model.matrix(~0 + primed.pheno + sce[,!all.pheno=="naive"]$batch)
y.vs.p <- estimateDisp(y.vs.p, design.vs.p)
fit.vs.p <- glmFit(y.vs.p, design.vs.p)

chosen.pheno <- which(levels(primed.pheno)=="transition")
result.logFC <- result.PValue <- list()
for (pheno in seq_len(nlevels(primed.pheno))) {
    if (pheno==chosen.pheno) { next }
    contrast <- numeric(ncol(design.vs.p))
    contrast[chosen.pheno] <- 1
    contrast[pheno] <- -1
    res <- glmLRT(fit.vs.p, contrast=contrast)
    con.name <- paste0('vs.', levels(primed.pheno)[pheno]) 
    result.logFC[[con.name]] <- res$table$logFC 
    result.PValue[[con.name]] <- res$table$PValue
}


marker_tp <- cbind(unlist(result.logFC["vs.primed"]), unlist(result.PValue["vs.primed"]))
rownames(marker_tp) <- rownames(y)
colnames(marker_tp) <- c("logFC", "PValue")
marker_tp <- marker_tp[order(marker_tp[,"PValue"]),]
write.table(file=paste0(output, "pvst_marker.tsv"), marker_tp, sep="\t", quote=FALSE, col.names = NA) 
```



```{r}
# Comparison
nt1 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="naive"], rownames(marker_nt_1)[1:10], 
               show_violin = T, colour_by = "phenotype")
nt2 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="transition"], rownames(marker_nt_1)[1:10], 
               show_violin = T, colour_by = "phenotype")
nt3 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="naive"], rownames(markerset.nt)[1:10], 
               show_violin = T, colour_by = "phenotype")
nt4 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="transition"],
                      rownames(markerset.nt)[1:10], 
               show_violin = T, colour_by = "phenotype")
multiplot(nt1, nt2, nt3, nt4, cols = 2)

tp1 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="primed"], marker_tp_1[1:10], 
               show_violin = T, colour_by = "phenotype")
tp2 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="transition"], marker_tp_1[1:10], 
               show_violin = T, colour_by = "phenotype")
tp3 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="primed"], rownames(marker_tp)[1:10], 
               show_violin = T, colour_by = "phenotype")
tp4 <- plotExpression(sce_trans[,pData(sce_trans)$phenotype=="transition"], rownames(marker_tp)[1:10], 
               show_violin = T, colour_by = "phenotype")
multiplot(tp1, tp2, tp3, tp4, cols=2)
```


```{r}
sce_trans <- readRDS(file = "~/Documents/vMeyenn/NaiveHESC2016/objects/new_sce_trans")
sce_p<- sce_trans[,which(sce_trans$phenotype=="primed")]
sce_n<- sce_trans[,which(sce_trans$phenotype=="naive")]
sce_t<- sce_trans[,which(sce_trans$phenotype=="transition")]

sce_p$phenotype <- factor(sce_p$phenotype, levels = c("primed", "naive", "transition"))
sce_n$phenotype <- factor(sce_n$phenotype, levels = c("primed", "naive", "transition"))
sce_t$phenotype <- factor(sce_t$phenotype, levels = c("primed", "naive", "transition"))

# naive vs trans

nt1 <- plotExpression(sce_n, c("SDC1", "CDH2", "ITGA5", "ITGA2", "ABCG2", "NRP1", "ENG", "L1CAM", "ITGA1"), 
               show_violin = T, colour_by = "phenotype")
nt2 <- plotExpression(sce_t, c("SDC1", "CDH2", "ITGA5", "ITGA2", "ABCG2", "NRP1", "ENG", "L1CAM", "ITGA1"), 
               show_violin = T, colour_by = "phenotype")


# primed vs trans

pt1 <- plotExpression(sce_p, c("PVR", "IL6R", "TNFSF9", "ITGAM", "F3", "ANPEP", "CDH5", "ABCG2", "ADAM8", "CDCP1", "ICAM1" ), 
                      show_violin = T, colour_by = "phenotype")
pt2 <- plotExpression(sce_t, c("PVR", "IL6R", "TNFSF9", "ITGAM", "F3", "ANPEP", "CDH5", "ABCG2", "ADAM8", "CDCP1", "ICAM1" ), 
                      show_violin = T, colour_by = "phenotype")

# trans vs both

t1 <- plotExpression(sce_n, c("VIM", "GATA3", "DPPA5"), show_violin = T, colour_by = "phenotype")
t2 <- plotExpression(sce_t, c("VIM", "GATA3", "DPPA5"), show_violin = T, colour_by = "phenotype")
t3 <- plotExpression(sce_p, c("VIM", "GATA3", "DPPA5"), show_violin = T, colour_by = "phenotype")


pdf(file = "~/Desktop/ConfirmMarkers.pdf")
multiplot(nt1, nt2, cols = 1)
multiplot(pt1, pt2, cols=1)
multiplot(t1,t2,t3, cols=1)
# Interesting: DPPA5, GATA3, ABCG2
par(mfrow=c(1,2))
plot(exprs(sce_n["GATA3",]), exprs(sce_n["ABCG2",]), main = "naive", pch=16)
plot(exprs(sce_t["GATA3",]), exprs(sce_t["ABCG2",]), main = "trans", pch=16)

par(mfrow=c(1,2))
plot(exprs(sce_n["DPPA5",]), exprs(sce_n["ABCG2",]), main = "naive", pch=16)
plot(exprs(sce_t["DPPA5",]), exprs(sce_t["ABCG2",]), main = "trans", pch=16)

par(mfrow=c(1,2))
plot(exprs(sce_n["DPPA5",]), exprs(sce_n["PTN",]), main = "naive", pch=16)
plot(exprs(sce_t["DPPA5",]), exprs(sce_t["PTN",]), main = "trans", pch=16)

dev.off()

```

